### ISSUE TITLE
Rendering issue in perspective mode

### ISSUE THREAD

**Issue by simonyangme** [pwmarcz/autotable#14]
Hi, there seems to be rendering issues when in perspective mode on macOS. I'm running on an M1 MacBook Air running a non-beta OS. I've attached a screenshot.
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/48696/124657970-065a4680-de58-11eb-85f4-618364a88df6.png">

**Comment by riichinomics** [comment]
Does this happen all the time, or after a certain action? Does it start
happening after a while? What browser are you using?

**Comment by simonyangme** [comment]
Ah, sorry I forgot to mention this is in Safari. This seems to happen regardless of game state. Here's what it looks like after just pressing `p` after loading the page.
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/48696/124676922-4c250800-de74-11eb-827f-46749e488692.png">

**Comment by pwmarcz** [comment]
I see the same effect in perspective mode, in Chrome but not in Firefox, and on only one on my machines (Linux, Intel graphics). The fix I just committed worked for me.

@simonyangme Can you check it now (on https://pwmarcz.pl/autotable/)?

**Comment by simonyangme** [comment]
Looks like it's fixed on my end as well. Thanks!
