### ISSUE TITLE
File format is not support in blender by make build

### ISSUE THREAD

**Issue by sunnytse0326** [pwmarcz/autotable#32]
When I try to make build with the command of "blender img/models.blend --background --python export.py -- img/models.auto.glb", I face the following issue:

File format is not supported in file '/Users/sunnytse0326/Desktop/autotable/img/models.blend'.

May I ask how can it be solved?

**Comment by riichinomics** [comment]
It's probably a blender version problem.

**Comment by sunnytse0326** [comment]
I am using the latest version 3.5, and I tried to install the older version from 2.79 - 2.93, which is also not working. Btw, I am using mac.

**Comment by pwmarcz** [comment]
Hi. The `models.blend` file is stored in Git LFS. Is it possible that you don't have Git LFS installed, and the actual file did not download?

(If Git LFS doesn't work, you should see a small text file instead of the 759 KB binary file.)

**Comment by sunnytse0326** [comment]
Hi, I installed the Git LFS by using homebrew, and now the version is 3.3.0. After that, I removed all the files and pulled it again. It also shows the error.

<img width="922" alt="Screenshot 2023-05-24 at 12 48 22 AM" src="https://github.com/pwmarcz/autotable/assets/1163955/b57582d7-d905-4604-a861-75f13b7a1d7c">

**Comment by pwmarcz** [comment]
Hi, just to make sure:
- how large is your `models.blend` file?
- did you install Git LFS, run `git lfs install`, and pull from the Github repo again?

**Comment by sunnytse0326** [comment]
Hi, it works now after I tried `git lfs install`. Thanks for the help! Much appreciated!
