### ISSUE TITLE
Face down tiles placed in extra discard area freezes game state

### ISSUE THREAD

**Issue by Daikyi** [pwmarcz/autotable#33]
Normally tiles cannot be placed facedown into the external discard area to the right of a given player's respective (third row of discards, 7th and onward tiles), however this can be circumvented if the tile is already face down in the discard pile (e.g. during wind draw distribution)

If that face-down tile is moved from the discard area to the extra discards, the game completely freezes up, and no other actions can occur.

**Comment by pwmarcz** [comment]
Thanks for reporting this! It should be fixed now.
