### ISSUE TITLE
Flowers and other special tiles?

### ISSUE THREAD

**Issue by joshk0** [pwmarcz/autotable#7]
It would be nice to play other variants of mahjong with this platform.

One part of making this platform accessible to other rulesets are flowers and seasons.

Since it isalready possible to customize akadora at a very granular level, my guess is that it would not be that hard to slide in extra tiles and include them in games as you wish. However, they will add to the total tiles in the wall and that will affect all code around dealing and wall building. For example, each of the 4 walls in HK mahjong is 18 tiles wide, because of the addition of 4 flowers and 4 seasons.

**Comment by joshk0** [comment]
cc @riichinomics in case you want to try to include that in your own variant

**Comment by riichinomics** [comment]
The readme says that pwmarcz is not interested in supporting other variants of mahjong. I'm also not super interested in non riichi mahjong but if there are some svg assets available for the flower tiles I may patch them in to my fork.

**Comment by joshk0** [comment]
OK ! I'll find those for you. Thanks for considering it!

**Comment by joshk0** [comment]
https://en.wikipedia.org/wiki/Mahjong_tiles#Contents

It looks like wikipedia has a pretty decent set of SVG formatted tiles for everything. But i think that for autotable we need to crop away the isometric tile backs.

@riichinomics - If you are interested in talking more about it I have opened the issue on your fork.

**Comment by joshk0** [comment]
Moved to riichinomics fork.
